[build]
  command = "npm run build && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "20"
  RUBY_VERSION = "3.3.0"
  NODE_ENV     = "production"
  JEKYLL_ENV   = "production"

[[headers]]
  for = "*.*"
  [headers.values]
    cache-control = "max-age=604800"
