[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  exclude = [
    # By file Path
    './public/appbar.html',
    './public/footer.html',
    './public/more-questions.html',
    # By Glob pattern
    './public/~~*.html'
  ]